### ISSUE TITLE
Index out of bounds error

### ISSUE THREAD

**Issue by tqwewe** [stillonearth/bevy_rl_shooter#5]
When building and running with `--mode train`, I get an error:

```
❯ ./target/release/bevy_rl_shooter --mode train
2022-12-24T13:11:06.217342Z  INFO bevy_render::renderer: AdapterInfo { name: "AMD Radeon Pro 5500M", vendor: 0, device: 0, device_type: DiscreteGpu, driver: "", driver_info: "", backend: Metal }
2022-12-24T13:11:06.692820Z  INFO gotham::start:  Gotham listening on http://127.0.0.1:7878
thread 'Compute Task Pool (4)' panicked at 'index out of bounds: the len is 0 but the index is 0', src/actors.rs:133:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/ari/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_tasks-0.9.1/src/task_pool.rs:273:45
```

**Comment by stillonearth** [comment]
This regression was introduced in `bevy_rl` 0.9.4 and fixed in 0.9.5 [a853f53](https://github.com/stillonearth/bevy_rl_shooter/commit/6d6c582219805c18703194750d46924c8ed6636d)
